#!/bin/bash

. .before

NAME=attr
VERSION=2.4.47

tar xf /import/sources/$NAME-$VERSION.src.tar.gz
cd $NAME-$VERSION

sed -i -e 's|/@pkg_name@|&-@pkg_version@|' include/builddefs.in

sed -i -e "/SUBDIRS/s|man[25]||g" man/Makefile

sed -i 's:{(:\\{(:' test/run

./configure --prefix=/usr \
            --disable-static

make

make install install-dev install-lib
chmod -v 755 /usr/lib/libattr.so

mv -v /usr/lib/libattr.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libattr.so) /usr/lib/libattr.so


