#!/bin/bash

. .before

NAME=automake
VERSION=1.15.1

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.15.1

make

make install
