#!/bin/bash

. .before

NAME=binutils
VERSION=2.29

env
tar xf /import/sources/$NAME-$VERSION.tar.bz2
cd $NAME-$VERSION

expect -c "spawn ls"

mkdir -v build
cd       build

../configure --prefix=/usr       \
             --enable-gold       \
             --enable-ld=default \
             --enable-plugins    \
             --enable-shared     \
             --disable-werror    \
             --with-system-zlib

make tooldir=/usr

make tooldir=/usr install
