#!/bin/bash

. .before

NAME=bzip2
VERSION=1.0.6

tar xf /import/sources/$NAME-$VERSION.tar.gz
cd $NAME-$VERSION

patch -Np1 -i /import/sources/bzip2-1.0.6-install_docs-1.patch

sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile

sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

make -f Makefile-libbz2_so
make clean

make

make PREFIX=/usr install

cp -v bzip2-shared /bin/bzip2
cp -av libbz2.so* /lib
ln -svf ../../lib/libbz2.so.1.0 /usr/lib/libbz2.so
rm -v /usr/bin/{bunzip2,bzcat,bzip2}
ln -svf bzip2 /bin/bunzip2
ln -svf bzip2 /bin/bzcat
