#!/bin/bash

. .before

NAME=gawk
VERSION=4.1.4

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

./configure --prefix=/usr

make

make install

mkdir -v /usr/share/doc/gawk-${VERSION}
cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-${VERSION}


