#!/bin/bash

. .before

NAME=gdbm
VERSION=1.13

tar xf /import/sources/$NAME-$VERSION.tar.gz
cd $NAME-$VERSION

./configure --prefix=/usr \
            --disable-static \
            --enable-libgdbm-compat

make

make install
