#!/bin/bash

. .before

NAME=gettext
VERSION=0.19.8.1

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

sed -i '/^TESTS =/d' gettext-runtime/tests/Makefile.in &&
sed -i 's/test-lock..EXEEXT.//' gettext-tools/gnulib-tests/Makefile.in

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-0.19.8.1

make

make install
chmod -v 0755 /usr/lib/preloadable_libintl.so
