#!/bin/bash

. .before

NAME=kbd
VERSION=2.0.4

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

patch -Np1 -i /import/sources/kbd-2.0.4-backspace-1.patch

sed -i 's/\(RESIZECONS_PROGS=\)yes/\1no/g' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

PKG_CONFIG_PATH=/tools/lib/pkgconfig ./configure --prefix=/usr --disable-vlock

make

make install

mkdir -v       /usr/share/doc/kbd-2.0.4
cp -R -v docs/doc/* /usr/share/doc/kbd-2.0.4
