#!/bin/bash

. .before

NAME=libcap
VERSION=2.25

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

sed -i '/install.*STALIBNAME/d' libcap/Makefile

make

make RAISE_SETFCAP=no lib=lib prefix=/usr install
chmod -v 755 /usr/lib/libcap.so

mv -v /usr/lib/libcap.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libcap.so) /usr/lib/libcap.so

