#!/bin/bash

. .before

NAME=man-db
VERSION=2.7.6.1

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

./configure --prefix=/usr                        \
            --docdir=/usr/share/doc/man-db-2.7.6.1 \
            --sysconfdir=/etc                    \
            --disable-setuid                     \
            --enable-cache-owner=bin             \
            --with-browser=/usr/bin/lynx         \
            --with-vgrind=/usr/bin/vgrind        \
            --with-grap=/usr/bin/grap

make

make install

sed -i "s:man man:root root:g" /usr/lib/tmpfiles.d/man-db.conf

