#!/bin/bash

. .before

NAME=pkg-config
VERSION=0.29.2

tar xf /import/sources/$NAME-$VERSION.tar.gz
cd $NAME-$VERSION

./configure --prefix=/usr              \
            --with-internal-glib       \
            --disable-host-tool        \
            --docdir=/usr/share/doc/pkg-config-$VERSION

make

make install


