#!/bin/bash

. .before

NAME=procps-ng
VERSION=3.3.12

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

./configure --prefix=/usr                            \
            --exec-prefix=                           \
            --libdir=/usr/lib                        \
            --docdir=/usr/share/doc/procps-ng-3.3.12 \
            --disable-static                         \
            --disable-kill                           \
            --with-systemd

make

make install

mv -v /usr/lib/libprocps.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libprocps.so) /usr/lib/libprocps.so
