#!/bin/bash

. .before

NAME=sed
VERSION=4.4

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

sed -i 's/usr/tools/'                 build-aux/help2man
sed -i 's/testsuite.panic-tests.sh//' Makefile.in

./configure --prefix=/usr --bindir=/bin

make

make install
