#!/bin/bash

. .before

NAME=tar
VERSION=1.29

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

FORCE_UNSAFE_CONFIGURE=1  \
./configure --prefix=/usr \
            --bindir=/bin

make

make install
make -C doc install-html docdir=/usr/share/doc/tar-${VERSION}

