#!/bin/bash

. .before

NAME=util-linux
VERSION=2.30.1

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

mkdir -pv /var/lib/hwclock

./configure ADJTIME_PATH=/var/lib/hwclock/adjtime   \
            --docdir=/usr/share/doc/util-linux-2.30.1 \
            --disable-chfn-chsh  \
            --disable-login      \
            --disable-nologin    \
            --disable-su         \
            --disable-setpriv    \
            --disable-runuser    \
            --disable-pylibmount \
            --disable-static     \
            --without-python

make

make install
