#!/bin/bash

. .before

NAME=binutils
VERSION=2.29

tar xf /import/sources/$NAME-$VERSION.tar.bz2
cd $NAME-$VERSION

mkdir -v build
cd       build

../configure --prefix=/tools            \
             --with-sysroot=$LFS        \
             --with-lib-path=/tools/lib \
             --target=$LFS_TGT          \
             --disable-nls              \
             --disable-werror

make

mkdir -v /tools/lib && ln -sv lib /tools/lib64

make install
