#!/bin/bash

. .before

cd $LFS

mkdir -pv $LFS/{dev,proc,sys,run}

rm -f dev/console
rm -f dev/null
mkdir -p dev

mknod -m 600 dev/console c 5 1
mknod -m 666 dev/null c 1 3

mkdir -pv bin
ln -vsf /tools/bin/bash bin/bash
