#!/bin/bash

. .before

NAME=gettext
VERSION=0.19.8.1

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

cd gettext-tools
EMACS="no" ./configure --prefix=/tools --disable-shared

make -C gnulib-lib
make -C intl pluralx.c
make -C src msgfmt
make -C src msgmerge
make -C src xgettext

cp -v src/{msgfmt,msgmerge,xgettext} /tools/bin