#!/bin/bash

. .before

NAME=gcc
VERSION=7.2.0

tar xf /import/sources/$NAME-$VERSION.tar.xz
cd $NAME-$VERSION

mkdir -v build
cd       build

../libstdc++-v3/configure           \
    --host=$LFS_TGT                 \
    --prefix=/tools                 \
    --disable-multilib              \
    --disable-nls                   \
    --disable-libstdcxx-threads     \
    --disable-libstdcxx-pch         \
    --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/$VERSION

make

make install
