#!/bin/bash

. .before

NAME=tcl-core
VERSION=8.6.7

tar xf /import/sources/${NAME}${VERSION}-src.tar.gz
cd tcl${VERSION}

cd unix
./configure --prefix=/tools

make

make install

chmod -v u+w /tools/lib/libtcl8.6.so

make install-private-headers

ln -sv tclsh8.6 /tools/bin/tclsh
